// Season 2 curation: research/s2/*.json + these decisions → data/s2.js (node tools/build-season.js 2).
// Reconciliation notes and every judgment call are in notes.md.
const S = (ep, s, note) => (note ? { ep, s, note } : { ep, s });
const L = (track, rung, moves = []) => ({ track, rung, moves });
const M = (ep, dir, text, to) => (to ? { ep, dir, to, text } : { ep, dir, text });

// police.json writes its relationship labels in lower case; capitalize them (explicit labels below win).
function capitalizedPoliceLabels() {
  const rels = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, 'police.json'), 'utf8')).relationships;
  return Object.fromEntries(rels.filter(r => /^[a-z]/.test(r.label))
    .map(r => [`${r.source}>${r.target}>${r.type}`, r.label[0].toUpperCase() + r.label.slice(1)]));
}

module.exports = {
  label: 'Season two', year: 2003,

  factions: {
    union:     { label: "Stevedores' Union", short: 'Union', color: '--harbor', anchor: [90, 215] },
    greeks:    { label: 'The Greeks', short: 'Greeks', color: '--olive', anchor: [-200, -215] },
    barksdale: { label: 'Barksdale Organization', short: 'Barksdale', color: '--sodium', anchor: [-480, 10] },
    street:    { label: 'The Street', short: 'Street', color: '--rose', anchor: [-240, 200] },
    police:    { label: 'Police & FBI', short: 'Police', color: '--fluoro', anchor: [440, -10] },
    law:       { label: 'Courts & Politics', short: 'Law', color: '--violet', anchor: [150, -215] },
    civilian:  { label: 'Family & Civilians', short: 'Civilian', color: '--stone', anchor: [360, 220], loose: true },
  },

  relTypes: {
    supply: { g: 'allies', label: 'Supply', out: 'Supplies', in: 'Supplied by', edge: ['supplies', 'buys from'], dist: 100 },
  },
  statuses: {
    inside: { label: 'Running it from prison', stamp: 'In prison', color: 'var(--sodium)' },
  },

  quickPicks: ['nick', 'ziggy', 'frank', 'ott', 'daniels', 'carver', 'prez', 'mcnulty', 'burrell', 'bodie', 'stringer', 'mouzone'],

  sources: [
    { file: 'greeks.json', idMap: { choksey: 'sam' } },
    { file: 'police.json' },
    { file: 'barksdale.json' },
    { file: 'union.json' },
  ],
  episodes: { file: 'episodes.json', idMap: { choksey: 'sam' }, speakers: { vondas: 'Vondas' } },
  factionMap: { mdta: 'police', prison: 'law', eastside: 'street' },

  characters: [
    // ---------------------------------------------------------------- returning: Barksdale and the street
    ['avon', { tier: 1, short: 'Avon', title: 'Kingpin, running it from prison',
      unit: 'In prison',
      role: 'Kingpin, serving his sentence and running the organization through Stringer\'s and Brianna\'s visits',
      roleEnd: 'Still the kingpin in prison, with his first parole hearing moved up 12 months; lets Stringer partner with Prop Joe',
      status: [S(0, 'inside', 'Serving his sentence; still makes the big calls')],
      ladder: L('game', 'kingpin', [
        M(3, 'side', 'On "Avon\'s call", Stringer has the guard Tilghman sold a poisoned package.'),
        M(4, 'up', 'Gives Tilghman up through Levy; his first parole hearing moves up 12 months.'),
        M(7, 'side', 'Refuses to share the towers with Prop Joe: "It\'s not even a thought."'),
        M(9, 'side', 'Sends to New York for Brother Mouzone rather than give up territory.'),
        M(12, 'down', 'Gives in on the Prop Joe deal: "You run it as you see fit. At least until I get home."'),
      ]),
      pathNote: 'Still the king from a cell: he picks the supplier, frames a guard for an earlier parole hearing and vetoes the deal. By the finale the business has outgrown his veto.' }],
    ['stringer', { tier: 1, short: 'Stringer', title: 'Second-in-command; runs it outside',
      bio: 'With Avon in prison, Stringer runs the business from a funeral home and keeps taking economics classes. The New York connection drops the Barksdales and the Atlanta product is weak, so he rebrands it, then trades three towers to Prop Joe for good product against Avon\'s wishes. He starts an affair with Donette, pays a contact from Washington to have D\'Angelo killed in prison and keeps it from Avon, and gets rid of Brother Mouzone by lying to Omar.',
      moments: [
        { ep: 5, text: 'Asks his economics teacher how to sell an inferior product, then runs a class for his dealers: new names, new cap colors.' },
        { ep: 6, text: 'Pays a contact from Washington for a job inside the prison that "can\'t come back" on him. D\'Angelo is strangled in the prison library the same episode.' },
        { ep: 7, text: 'The contact tells him the prison is calling it a hanging and asks whether Avon knew. Stringer warns him to keep it out of Avon\'s ear.' },
        { ep: 9, text: 'Secretly gives Prop Joe towers 734, 770 and 221 for product at Joe\'s cost, despite Avon\'s refusal.' },
        { ep: 11, text: 'Meets Omar at Butchie\'s bar and tells him Brother Mouzone did the "extras" to Brandon.' },
      ],
      status: [S(12, 'promoted', 'Avon lets him run it with Prop Joe "until I get home"')],
      ladder: L('game', 'second', [
        M(1, 'side', 'Loses the New York connection; the Atlanta product that replaces it is weak.'),
        M(6, 'side', 'Pays a contact from Washington for a job inside the prison, behind Avon\'s back.'),
        M(9, 'up', 'Gives Prop Joe three towers for product at cost, without Avon\'s approval.'),
        M(11, 'side', 'Points Omar at Brother Mouzone with a lie about Brandon.'),
        M(12, 'up', 'Avon approves the Prop Joe partnership.'),
      ]),
      pathNote: 'Second on paper, but he makes the season\'s biggest calls himself: D\'Angelo, the towers, Mouzone. Each one goes behind Avon\'s back.' }],
    ['weebey', { tier: 2, short: 'Wee-Bey', title: 'Inmate; Avon\'s friend inside', unit: 'In prison',
      status: [S(0, 'imprisoned', 'Serving time for the murders he confessed to')],
      ladder: L('game', 'enforcer'),
      pathNote: 'Still the name on the enforcer rung, but locked up. With him inside and Stinkum dead, Avon has to hire muscle from New York.' }],
    ['bird', { tier: 3, short: 'Bird', title: 'Soldier; on trial for Gant', unit: 'In jail',
      status: [S(0, 'arrested', 'Jailed awaiting trial for the Gant murder'), S(6, 'convicted', 'Convicted on Omar\'s testimony')],
      ladder: L('game', 'soldiers', [M(6, 'out', 'Convicted of killing William Gant; Judge Phelan signals a life sentence.')]) }],
    ['dangelo', { tier: 1, short: "D'Angelo", title: "Inmate; Avon's nephew", unit: 'In prison',
      role: 'Serving 20 years in the same prison as Avon',
      roleEnd: 'Strangled in the prison library; the death is staged as a hanging',
      bio: 'Serving twenty years in the same prison as Avon, D\'Angelo is getting high and working in the prison library. After the poisoned-drug deaths he refuses any part of Avon\'s scheme and asks his mother to keep Avon, Stringer and Donette away. In episode 6 another inmate strangles him in the library and leaves him hanging from a doorknob. Stringer had paid a contact from Washington for the job, and the family is left to believe it was suicide.',
      status: [S(0, 'imprisoned', 'Serving 20 years'), S(6, 'dead', 'Strangled in the prison library; staged as a hanging')],
      offLadder: 'Twenty years in, he walks away from the family business. In episode 4 he tells Avon he wants no part of what he does.' }],
    ['bodie', { tier: 1, short: 'Bodie', title: 'Crew chief, the towers',
      ladder: L('game', 'crewchief', [
        M(1, 'side', 'Trusted with the Philadelphia run; the car comes back empty and Stringer has him tailed.'),
        M(8, 'side', 'Drives an independent crew off a corner with Poot.'),
        M(9, 'out', 'Brought in after a stray bullet kills a boy; sees through the detectives\' bluff and walks.'),
        M(10, 'down', 'Has to share the towers with Prop Joe\'s crew under Stringer\'s deal.'),
      ]),
      pathNote: 'A crew chief now, tested before he\'s trusted. The weak package costs him customers, his turf war ends with a child dead, and Stringer\'s deal hands half his towers to the East Side.' }],
    ['poot', { tier: 2, short: 'Poot', title: 'Runs the Pit',
      ladder: L('game', 'crewchief', [M(8, 'side', 'Gathers a crew with Bodie to drive an independent crew off their corner.')]) }],
    ['puddin', { tier: 3, short: "Puddin'", title: "Bodie's second in the towers", ladder: L('game', 'dealers') }],
    ['brianna', { tier: 2, short: 'Brianna', title: "Avon's sister; D'Angelo's mother",
      offLadder: 'Family, not rank. She carries messages between Avon, Stringer and her son.' }],
    ['levy', { tier: 2, short: 'Levy', title: 'Barksdale defense attorney', faction: 'law', unit: 'Defense bar',
      offLadder: 'The organization\'s lawyer. He wins Avon an earlier parole hearing, but he isn\'t in the chain of command.' }],
    ['omar', { tier: 1, short: 'Omar', title: 'Stick-up man',
      offLadder: 'Omar robs the game instead of climbing it. This season he also takes the stand.' }],
    ['propjoe', { tier: 1, short: 'Prop Joe', title: 'East Side drug boss', faction: 'street', unit: 'East Side',
      offLadder: 'He runs his own East Side organization. His power this season is supply: the Greeks\' product buys him three Barksdale towers.' }],
    ['bubbles', { tier: 2, short: 'Bubbles', initials: 'BU', title: 'Addict; informant',
      offLadder: 'He works for the police, not in it. This season he finds Omar for McNulty and tips Kima to the tower deal.' }],
    ['johnny', { tier: 3, short: 'Johnny', title: "Addict; Bubbles' partner" }],
    ['donette', { tier: 3, short: 'Donette', initials: 'DO', title: "D'Angelo's girlfriend; Stringer's lover", faction: 'civilian' }],
    ['roberto', { tier: 3, short: 'Roberto', initials: 'RO', title: 'Supplier, New York', actor: null,
      status: [S(1, 'gone', 'Targeted by the DEA; his people drop the Barksdales')] }],

    // ---------------------------------------------------------------- new: Barksdale, prison and the street
    ['shamrock', { tier: 2, short: 'Shamrock', title: "Stringer's right hand",
      ladder: L('game', 'soldiers', [
        M(1, 'side', 'Goes on the Philadelphia run with Bodie; Stringer has them tailed.'),
        M(3, 'side', 'Tails the guard Tilghman to his supplier.'),
        M(9, 'side', 'Drives Bodie to dump the guns after the boy\'s death.'),
      ]),
      pathNote: 'Always at Stringer\'s side, doing the jobs that need trust rather than a gun.' }],
    ['country', { tier: 3, short: 'Country', title: 'Soldier, on parole', ladder: L('game', 'soldiers') }],
    ['cherry', { initials: 'CY', tier: 3, short: 'Cherry', title: 'Runs the cut house', ladder: L('game', 'stash') }],
    ['mouzone', { initials: 'MO', tier: 2, short: 'Mouzone', name: 'Brother Mouzone', title: 'Hired gun from New York',
      bio: "A soft-spoken, bow-tied enforcer from New York whom Avon sends for to protect the towers. He arrives sooner than Stringer expected, shoots Cheese with rat shot to clear the East Side dealers out, and keeps them away just by sitting and reading. Omar, told by Stringer that Mouzone killed Brandon, shoots him at his motel door. From his hospital bed Mouzone turns down Stringer's help, tells him the agreement with Avon is \"absolved\" and says he will take care of the shooters himself.",
      status: [S(11, 'hospitalized', 'Shot by Omar at his motel door'), S(12, 'gone', 'Ends the deal with Avon and leaves')],
      ladder: L('game', 'enforcer', [
        M(9, 'up', 'Avon sends for him from New York to hold the towers, on retainer.'),
        M(10, 'side', 'Shoots Cheese with rat shot; the East Side crew leaves the towers.'),
        M(11, 'out', 'Shot by Omar, who was sent by Stringer\'s lie.'),
        M(12, 'out', 'Releases Avon from their agreement and leaves.'),
      ]),
      pathNote: 'Avon fills the empty enforcer rung by hiring, not promoting. The hire lasts three episodes.' }],
    ['lamar', { tier: 3, short: 'Lamar', title: "Mouzone's assistant",
      offLadder: 'He works for Mouzone, not for the Barksdales.' }],
    ['tilghman', { tier: 2, short: 'Tilghman', title: 'Prison guard; smuggles drugs inside', unit: 'State prison (guard)',
      status: [S(4, 'arrested', 'Charged after the drugs he smuggled in kill inmates')],
      offLadder: 'A guard who crossed Avon. Avon uses him to buy time off his own sentence.' }],
    ['vargas', { tier: 3, short: 'Vargas', initials: 'VA', title: 'Supplier, Atlanta', actor: null,
      offLadder: 'An outside supplier, never seen. Each Atlanta package is weaker than the last.' }],
    ['cheese', { initials: 'CS', tier: 2, short: 'Cheese', title: "Prop Joe's man on the street", faction: 'street',
      status: [S(10, 'injured', 'Shot with rat shot by Mouzone')],
      offLadder: 'Works for Prop Joe. Under Stringer\'s deal he runs a crew in three Barksdale towers until Mouzone drives him out.' }],
    ['butchie', { initials: 'BT', tier: 2, short: 'Butchie', title: "Bar owner; Omar's banker",
      offLadder: 'Independent. He banks Omar\'s money, sells to the guard Tilghman and brokers sit-downs.' }],
    ['dante', { tier: 3, short: 'Dante', title: "Omar's boyfriend and partner" }],
    ['kimmy', { tier: 3, short: 'Kimmy', title: 'Stick-up crew, with Tosha' }],
    ['tosha', { tier: 3, short: 'Tosha', name: 'Tosha', title: 'Stick-up crew, with Kimmy' }],

    // ---------------------------------------------------------------- returning: police, courts, politics, families
    ['burrell', { tier: 2, short: 'Burrell', title: 'Deputy Commissioner; next in line',
      role: 'Deputy Commissioner for Operations; the mayor\'s choice to succeed Frazier, pending a City Council vote',
      roleEnd: 'Moving into the commissioner\'s office now that the council votes are in',
      status: [S(9, 'promoted', 'The council votes are in; he moves up to commissioner')],
      ladder: L('job', 'deputy', [
        M(2, 'up', 'The mayor\'s choice to succeed Frazier, pending a City Council vote.'),
        M(2, 'side', 'Buys Valchek\'s council votes with a detail on Frank Sobotka: "Six men for six weeks."'),
        M(4, 'side', 'Gives the detail to Daniels and promises him a permanent unit.'),
        M(9, 'up', 'The votes are in: he moves into the commissioner\'s office.', 'commissioner'),
      ]),
      pathNote: 'Bought the top job with a favor: six men for six weeks against a stevedore, for one district\'s council votes.' }],
    ['rawls', { tier: 2, short: 'Rawls', title: 'Colonel, CID',
      ladder: L('job', 'colonel', [
        M(1, 'side', 'Tries to pass McNulty\'s floater to the county; the tide charts send it back.'),
        M(2, 'down', 'Loses the jurisdiction fight: fourteen Jane Does go up on his board.'),
        M(7, 'up', 'Hands the Jane Does to Daniels\' detail in return for his support.'),
        M(12, 'up', 'Celebrates the Jane Doe clearances.'),
      ]),
      pathNote: 'Promoted between seasons. All season he tries to keep fourteen murders off his books, and in the end they are cleared.' }],
    ['valchek', { tier: 1, short: 'Valchek', title: 'Major, Southeastern District',
      ladder: L('job', 'major', [
        M(2, 'up', 'Trades council votes for Burrell\'s confirmation in return for a detail on Frank Sobotka.'),
        M(3, 'up', 'Threatens to sink the confirmation and gets Daniels to run his detail.'),
        M(10, 'side', 'Takes the case to the FBI when the detail moves past Sobotka; Prez punches him.'),
        M(11, 'up', 'Watches the FBI arrest Sobotka at the union hall.'),
      ]),
      pathNote: 'A district major with a grudge and council votes to trade. That is enough to start a federal case.' }],
    ['daniels', { tier: 1, short: 'Daniels', title: 'Lieutenant; runs the detail',
      role: 'Lieutenant exiled to Evidence Control in the basement after the Barksdale case',
      bio: "After the Barksdale case, Daniels is sent to Evidence Control. He plans to put in his papers and practice law, until Valchek demands him by name to run the detail on Frank Sobotka. He uses that leverage to pick his own people and to get Burrell's promise of a permanent major case unit. He takes on Rawls's fourteen Jane Does in exchange for Rawls's support and McNulty, and follows the case past Sobotka to the Greek. The Greek escapes and Sobotka is murdered, but Burrell commits to keeping the crew together as a major case squad.",
      status: [S(0, 'desk', 'Exiled to Evidence Control'), S(4, 'active', 'Back in command: the detail')],
      ladder: L('job', 'lieutenant', [
        M(1, 'down', 'Exiled to Evidence Control in the basement after the Barksdale case.'),
        M(2, 'side', 'Tells Marla he will put in his papers and practice law.'),
        M(4, 'up', 'Valchek demands him by name. He takes the detail on condition it becomes a permanent unit and he picks his own people.'),
        M(4, 'side', 'Burrell dangles a major\'s posting. It doesn\'t come this season.'),
        M(7, 'up', 'Takes Rawls\'s Jane Does in return for Rawls\'s full support.'),
        M(12, 'up', 'Burrell commits to keeping his crew together as a major case squad in CID.'),
      ]),
      pathNote: 'Punished for the Barksdale case, then needed for Valchek\'s grudge. This time he negotiates: a permanent unit and his own people.' }],
    ['landsman', { tier: 2, short: 'Landsman', title: 'Sergeant, Homicide squad', ladder: L('job', 'sergeant') }],
    ['mcnulty', { tier: 1, short: 'McNulty', title: 'Marine Unit officer, then the detail',
      moments: [
        { ep: 1, text: 'Uses tide charts to prove the floater went into the water inside city limits, sending the case back to Rawls.' },
        { ep: 2, text: "Shows the container's air pipe was crushed deliberately, which makes the deaths homicides." },
        { ep: 6, text: 'Sleeps with Elena after a dinner date. In ep 7 she tells him she can never trust him again.' },
        { ep: 9, text: 'Goes undercover at the brothel as an English customer and is found in bed with two of the women when the raid team arrives.' },
        { ep: 12, text: 'With Kima, photographs Stringer meeting Proposition Joe and argues for that case.' },
      ],
      status: [S(0, 'reassigned', 'Punished with the Marine Unit'), S(8, 'active', 'Off the boat and onto the detail')],
      ladder: L('job', 'officer', [
        M(1, 'side', 'Uses tide charts to send the floater back to Rawls\'s Homicide unit.'),
        M(2, 'side', 'Proves the container deaths were murder: fourteen Jane Does for Rawls.'),
        M(4, 'down', 'Daniels asks for him; Rawls says "He quits or he drowns."'),
        M(8, 'up', 'Off the boat: Rawls lets him join the detail once Daniels takes the Jane Does.'),
        M(12, 'side', 'Photographs Stringer meeting Prop Joe and pitches the next case.'),
      ]),
      pathNote: 'Exiled to the boat for the Barksdale case, he gets back to real police work by handing fourteen murders to the man who exiled him.' }],
    ['bunk', { tier: 1, short: 'Bunk', title: 'Homicide detective',
      bio: "Bunk presses McNulty to find Omar for Bird's trial for the Gant murder, then catches the fourteen Jane Does with Freamon and port officer Beadie Russell. Rawls makes clear he expects them cleared, so Bunk works them out of Daniels' detail office. In the finale, Philadelphia port security tape puts Sergei at the crewman's abduction, and Sergei's admission that Vondas killed him clears the Jane Does.",
      ladder: L('job', 'detective', [
        M(2, 'side', 'Catches the fourteen Jane Does with Freamon.'),
        M(6, 'side', 'Bird is convicted of Gant\'s murder on Omar\'s testimony.'),
        M(12, 'up', 'Philadelphia port video breaks Sergei, and the Jane Does are cleared.'),
      ]),
      pathNote: 'Rawls makes clear the Jane Does get cleared or Bunk is out of Homicide. They get cleared.' }],
    ['freamon', { tier: 1, short: 'Freamon', title: 'Homicide detective, then the detail',
      status: [S(5, 'reassigned', 'Detailed to Daniels')],
      moments: [
        { ep: 2, text: 'Gets the Jane Does with Bunk.' },
        { ep: 5, text: 'Detailed to the Sobotka detail, he recognizes Frank Sobotka from his photo and links him to the Jane Does.' },
        { ep: 6, text: 'Finds $70,000 in union political contributions and ties the missing containers to Horseface.' },
        { ep: 8, text: "The decoy container gives the detail Vondas's phone number." },
        { ep: 12, text: 'Takes Nick Sobotka to the detail when he surrenders at the Southeastern desk.' },
      ],
      ladder: L('job', 'detective', [
        M(2, 'side', 'Gets the Jane Does with Bunk.'),
        M(5, 'up', 'Detailed to Daniels; ties Frank Sobotka to the dead women.'),
        M(6, 'up', 'Finds $70,000 in union political money and ties the lost cans to Horseface.'),
        M(8, 'up', 'The decoy container gives the detail Vondas\'s phone.'),
      ]),
      pathNote: 'Same rank as in Season 1, better company: Homicide, then the detail, where his paper trail drives the case.' }],
    ['kima', { tier: 1, short: 'Kima', title: 'Detective; leads the street team',
      status: [S(4, 'reassigned', 'Leaves her desk job to join the detail')],
      ladder: L('job', 'detective', [
        M(1, 'side', 'Working a desk in Asset Forfeiture, as she promised Cheryl.'),
        M(4, 'up', 'Daniels talks her back onto the street, over Cheryl\'s objections.'),
        M(5, 'up', 'Runs Herc and Carver\'s team on the detail, over a sergeant.'),
        M(12, 'side', 'Photographs Stringer meeting Prop Joe and pitches the next case.'),
      ]),
      pathNote: 'Rank doesn\'t decide who leads here: Daniels puts a detective over a sergeant.' }],
    ['herc', { tier: 2, short: 'Herc', title: 'Detective on the detail', reportsTo: 'kima',
      ladder: L('job', 'detective', [
        M(4, 'side', 'Picked for the detail by Daniels.'),
        M(8, 'down', 'Invents an informant, "Fuzzy Dunlop", to cover for a lost bug.'),
        M(12, 'side', 'Fed up with surveillance; says he\'ll go back to narcotics.'),
      ]),
      pathNote: 'Still looking for a "rabbi", a patron who can move him up.' }],
    ['carver', { tier: 2, short: 'Carver', title: 'Sergeant; reports to Greggs', reportsTo: 'kima',
      status: [S(5, 'reassigned', 'Joins the detail; his stripes don\'t count there')],
      ladder: L('job', 'sergeant', [
        M(2, 'side', 'Uniformed sergeant in the Southeastern, ticketing the stevedores\' cars on Valchek\'s orders.'),
        M(5, 'down', 'Daniels takes him onto the detail but puts him under Detective Greggs.'),
        M(12, 'side', 'Says he will apply for a sergeant\'s slot in the Western District.'),
      ]),
      pathNote: 'His stripes came from informing on Daniels. On Daniels\' detail they count for nothing.' }],
    ['prez', { tier: 2, short: 'Prez', title: "Detective; Valchek's son-in-law",
      bio: "Prez tells his father-in-law Valchek he wants to work cases, not chase rank, and is put on Valchek's first detail, where Lieutenant Grayson ignores his advice. His complaints to Valchek lead to Daniels taking over. He works the money trail and the vice angle. When Valchek storms in and insults him in front of the detail, Prez punches him, then hands Daniels his gun. Daniels gets the charges dropped in exchange for two months of midnight desk duty and a letter of apology.",
      status: [S(12, 'desk', 'Two months on the midnight desk for punching Valchek')],
      ladder: L('job', 'detective', [
        M(1, 'side', 'Turns down Valchek\'s plan to make him sergeant: "I want to work cases."'),
        M(2, 'side', 'Put on Valchek\'s first detail as its lead investigator.'),
        M(6, 'up', 'Works the union\'s money trail with Freamon.'),
        M(10, 'down', 'Punches Valchek in the detail office and hands Daniels his gun.'),
        M(12, 'down', 'Two months on the midnight desk and a letter of apology, then he can come back.'),
      ]),
      pathNote: 'His father-in-law kept him in the job. Hitting his father-in-law nearly ends it, and Daniels saves him.' }],
    ['cole', { tier: 3, short: 'Cole', title: 'Homicide detective', ladder: L('job', 'detective') }],
    ['norris', { tier: 3, short: 'Norris', title: 'Homicide detective', ladder: L('job', 'detective') }],
    ['polk', { tier: 3, short: 'Polk', title: 'Detective; first detail',
      ladder: L('job', 'detective', [M(4, 'side', 'Left off the detail when Daniels takes it over.')]) }],
    ['santangelo', { tier: 3, short: 'Santangelo', title: 'Patrol officer', ladder: L('job', 'officer') }],
    ['fitzhugh', { tier: 2, short: 'Fitz', title: 'FBI special agent',
      bio: "McNulty's FBI contact checks Glekas for him, and the inquiry reaches Agent Koutris in Washington, who plays Glekas down. When Valchek brings in the Bureau, Fitz works the case with the detail: he traces Vondas's texts and helps arrest Sergei. At the end he learns Koutris left the San Diego office more than a year ago for counterterrorism in Washington, and tells Daniels, off the record, that the leak came from the Bureau's side.",
      moments: [
        { ep: 9, text: 'Checks Glekas for McNulty; the inquiry reaches Agent Koutris in Washington.' },
        { ep: 10, text: 'Arrives at the detail with the FBI team and helps trace Vondas\'s text messages.' },
        { ep: 11, text: 'Arrests Sergei at his home with McNulty.' },
        { ep: 12, text: 'Learns Koutris is in counterterrorism in Washington and tells Daniels the leak wasn\'t from his people.' },
      ],
      offLadder: 'FBI, outside the BPD. He works out where the leak came from, and nothing is done about it.' }],
    ['reese', { tier: 3, short: 'Reese', initials: 'AR', title: 'FBI supervisor',
      offLadder: 'FBI supervisor, outside the BPD. The Bureau\'s interest is the union.' }],
    ['pearlman', { tier: 2, short: 'Pearlman', title: "Assistant State's Attorney",
      offLadder: 'A prosecutor, not a cop. She gets the wiretaps signed and offers Frank and Nick the deal.' }],
    ['nathan', { tier: 3, short: 'Nathan', title: 'ASA; prosecutes Bird' }],
    ['phelan', { tier: 3, short: 'Phelan', title: 'Circuit Court judge',
      offLadder: 'A judge, outside the department. This season he tries Bird.' }],
    ['davis', { tier: 3, short: 'Clay Davis', title: 'State senator' }],
    ['marla', { tier: 3, short: 'Marla', title: "Daniels' wife", role: "Daniels' wife, urging him to leave the department and practice law" }],
    ['elena', { tier: 3, short: 'Elena', title: "McNulty's estranged wife" }],
    ['cheryl', { tier: 3, short: 'Cheryl', initials: 'CH', title: "Kima's partner" }],
    ['shardene', { tier: 3, short: 'Shardene', title: "Freamon's girlfriend; nursing student",
      bio: 'Now in nursing school ("Lester\'s been pushing me"), Shardene connects Kima with a dancer friend who describes the trafficked Eastern European women and the madam who controls them.' }],

    // ---------------------------------------------------------------- new: police, port police, FBI
    ['beadie', { tier: 1, short: 'Beadie', title: 'Port police officer', unit: 'Port Authority police',
      status: [S(3, 'reassigned', 'Detailed to Homicide as port liaison'), S(12, 'active', 'Back on the job at the port')],
      offLadder: 'Port Authority police, not city police. She has no rank to climb here, only a case she was never meant to keep.' }],
    ['diggins', { initials: 'DG', tier: 3, short: 'Diggins', title: 'Marine Unit officer', ladder: L('job', 'officer') }],
    ['koutris', { initials: 'KO', tier: 2, short: 'Koutris', name: 'Agent Koutris', title: "FBI agent; the Greek's source", faction: 'police',
      offLadder: 'An FBI agent outside both chains, trading information with the Greek.' }],
    ['grayson', { tier: 3, short: 'Grayson', title: 'Lieutenant; first detail commander', actor: null, firstEp: 3,
      bio: 'Recommended by Burrell as "really good at property crimes", Lieutenant Grayson commands Valchek\'s first detail on Frank Sobotka. He ignores Prez\'s advice to pull phone records and look at union assets. When Valchek drops in, Grayson is out and the men are playing poker, so Valchek demands Daniels.',
      status: [S(4, 'reassigned', 'Detail handed to Daniels')],
      ladder: L('job', 'lieutenant', [M(4, 'down', 'Replaced by Daniels after Valchek finds the detail playing poker.')]) }],
    ['colvin', { tier: 3, short: 'Colvin', title: 'Major, Western District', ladder: L('job', 'major') }],
    ['randallfrazier', { tier: 3, short: 'Dr. Frazier', name: 'Randall Frazier', title: 'Medical examiner', faction: 'police', unit: "Medical Examiner's Office",
      offLadder: 'The medical examiner, outside the police ranks. His ruling turns thirteen accidents into thirteen homicides.' }],

    // ---------------------------------------------------------------- new: the union and the docks
    ['frank', { tier: 1, short: 'Frank', full: 'Francis Sobotka', title: 'Secretary-treasurer, Local 1514', unit: 'Local 1514 (checkers)',
      bio: "Secretary-treasurer of the checkers' local of the International Brotherhood of Stevedores. He takes the Greek's money per container and spends it on the union: lobbyists, campaign contributions and cash for members who cannot get work, all to get the C&D canal dredged and the grain pier rebuilt. A church-window feud with Major Valchek, the thirteen dead women in a Greek can, and his son's and nephew's crimes bring the police and the FBI down on him. Arrested, he agrees to cooperate, then goes alone to meet the Greek to help Ziggy. His body is pulled from the harbor in the finale.",
      status: [S(11, 'cooperating', 'Arrested and released; agrees to give up the Greeks'), S(12, 'dead', 'Body pulled from the harbor')],
      ladder: L('union', 'officers', [
        M(1, 'side', 'Wins the church window spot from Valchek, starting the feud.'),
        M(5, 'up', 'The Greek doubles, then triples, his fee per container.'),
        M(7, 'side', 'Asks Nat for one more year, though by agreement it is Ott\'s turn.'),
        M(10, 'side', 'Runs for re-election anyway.'),
        M(11, 'out', 'Arrested by the FBI at the union hall; his political support walks away.'),
        M(12, 'out', 'Pulled from the harbor. The members re-elect him anyway.'),
      ]),
      pathNote: 'Runs the local on the Greek\'s money: lobbyists, handouts, a church window. He breaks the union\'s rotation to stay on, and the money that keeps him there brings in the FBI.' }],
    ['nick', { tier: 1, short: 'Nick', full: 'Nicholas Sobotka', title: "Stevedore; Frank's go-between", unit: 'Local 47 (longshoremen)',
      status: [S(11, 'fugitive', 'Warrant out after drugs and cash turn up in his room'), S(12, 'cooperating', 'Surrenders and gives up the Greeks; protective custody')],
      ladder: L('union', 'junior', [
        M(1, 'side', 'Carries container numbers between Frank and Vondas; works his first day in two weeks.'),
        M(3, 'up', 'Steals a can of cameras with Ziggy and sells it to Glekas.'),
        M(6, 'up', 'Takes half his chemicals money in heroin and starts dealing.'),
        M(9, 'down', 'Vondas passes him down to White Mike for his re-ups.'),
        M(11, 'out', 'Police search his parents\' house; a warrant is issued.'),
        M(12, 'out', 'Turns himself in and cooperates. The next day there is still no work.'),
      ]),
      pathNote: 'Too junior to get a full week on the docks, so he climbs the only ladder that\'s hiring: the Greeks\'.' }],
    ['ziggy', { tier: 1, short: 'Ziggy', full: 'Chester Sobotka', title: "Checker; Frank's son", unit: 'Local 1514 (checkers)',
      status: [S(10, 'arrested', 'Charged with murdering Glekas')],
      ladder: L('union', 'junior', [
        M(1, 'down', 'Loses track of a container; Frank fires him on the spot, which nobody takes seriously.'),
        M(5, 'down', 'Cheese\'s crew beats him over a debt and burns his car.'),
        M(7, 'down', 'Nick takes over the heroin and pays him a share.'),
        M(10, 'out', 'Shoots Glekas dead over the car money and confesses.'),
      ]),
      pathNote: 'The boss\'s son, with no seniority and no respect. Every scheme to prove himself makes it worse, until the last one.' }],
    ['horseface', { tier: 2, short: 'Horseface', name: 'Horseface Pakusa', full: 'Thomas Pakusa', title: "Checker; loses the Greek's cans", unit: 'Local 1514 (checkers)',
      status: [S(11, 'arrested', 'Arrested by the FBI with Frank')],
      ladder: L('union', 'senior', [
        M(1, 'side', '"Loses" the Greek\'s can in the stacks on Frank\'s word.'),
        M(2, 'side', 'Steals Valchek\'s surveillance van and ships it overseas.'),
        M(5, 'side', 'Stonewalls the grand jury.'),
        M(11, 'out', 'Arrested by the FBI at the union hall.'),
      ]),
      pathNote: 'Frank\'s oldest friend on the docks, so he\'s the one who makes the cans disappear, and the one arrested beside Frank.' }],
    ['coxson', { tier: 2, short: 'Nat', title: 'President, Local 47', unit: 'Local 47 (longshoremen)',
      ladder: L('union', 'officers', [
        M(7, 'side', 'Holds Frank to their deal: this time it\'s Ott\'s turn.'),
        M(11, 'side', 'Won\'t look at Frank after the arrest.'),
      ]),
      pathNote: 'The other local\'s president, and the man whose votes decide Frank\'s post.' }],
    ['ott', { tier: 2, short: 'Ott', name: 'Ott', title: 'Checker; next in line to lead', unit: 'Local 1514 (checkers)',
      ladder: L('union', 'senior', [
        M(7, 'up', 'Under the union\'s rotation, the next term as secretary-treasurer is his.'),
        M(10, 'down', 'Frank decides to run again.'),
        M(12, 'side', 'Stands aside; the members back the dead Frank.'),
      ]),
      pathNote: 'A deal says it\'s his turn. Frank\'s need for one more year outweighs the deal, and so does Frank\'s death.' }],
    ['johnnyfifty', { tier: 3, short: 'Johnny Fifty', name: 'Johnny Fifty', title: "Checker; the cousins' friend", unit: 'Local 1514 (checkers)',
      ladder: L('union', 'junior', [M(5, 'side', 'Served a grand jury summons; says nothing.')]) }],
    ['maui', { tier: 3, short: 'Maui', title: "Checker; Ziggy's tormentor", unit: 'Local 1514 (checkers)', ladder: L('union', 'members'),
      moments: [
        { ep: 4, text: "Spills coffee on Ziggy's new coat and mocks him for stealing; Ziggy gets back at him with a crude prank." },
        { ep: 5, text: "Won't inform for Beadie, but points her to the port computer." },
        { ep: 8, text: 'Beats Ziggy in a fight and strands him on top of a container with a forklift.' },
      ] }],
    ['lala', { tier: 3, short: 'La La', title: "Longshoreman; Nick's friend", unit: 'Local 47 (longshoremen)', ladder: L('union', 'junior') }],
    ['littlebigroy', { tier: 3, short: 'Little Big Roy', title: 'Senior stevedore', unit: 'Local 47 (longshoremen)',
      ladder: L('union', 'senior', [M(11, 'side', 'Lends Frank his union card so Frank can work a ship.')]) }],
    ['newcharles', { initials: 'NE', tier: 3, short: 'New Charles', title: 'Longshoreman', unit: 'Local 47 (longshoremen)',
      status: [S(7, 'injured', 'Loses a leg in a dock accident')],
      ladder: L('union', 'members', [M(7, 'out', 'Crushed under a load; he loses his leg.')]) }],
    ['ringo', { tier: 3, short: 'Ringo', title: 'Checker short of days', unit: 'Local 1514 (checkers)',
      ladder: L('union', 'junior', [M(3, 'side', 'Ready to switch locals; Frank sends him to Delores for cash.')]) }],
    ['delores', { tier: 3, short: 'Delores', title: "Runs the stevedores' bar" }],
    ['louis', { tier: 2, short: 'Louis', title: "Frank's brother; Nick's father",
      offLadder: 'Out of work since the shipyard closed, and out of the union with it. He turns down the paid board seat Frank gets him.' }],
    ['joan', { tier: 3, short: 'Joan', title: "Nick's mother" }],
    ['aimee', { tier: 3, short: 'Aimee', title: "Nick's girlfriend" }],
    ['prissy', { tier: 3, short: 'Prissy', name: 'Prissy', title: 'Old friend of Nick and Ziggy' }],
    ['lewandowski', { tier: 3, short: 'Lewandowski', name: 'Father Lewandowski', title: "Priest, St. Casimir's" }],
    ['dibiago', { tier: 3, short: 'DiBiago', title: 'Lobbyist for the union', faction: 'law' }],
    ['krawczyk', { tier: 3, short: 'Krawczyk', title: "Developer; Valchek's friend", faction: 'law' }],

    // ---------------------------------------------------------------- new: the Greeks and their customers
    ['greek', { tier: 1, short: 'The Greek', initials: 'G', name: 'The Greek', title: 'Head of the smuggling ring',
      status: [S(12, 'gone', 'Leaves Baltimore before the raid')],
      offLadder: 'There is no ladder in the Greek\'s organization. People are paid, cut loose or killed, and the man at the top leaves before the police arrive.' }],
    ['vondas', { initials: 'VO', tier: 1, short: 'Vondas', name: 'Spiros Vondopoulos', alias: 'Vondas', title: "The Greek's second",
      status: [S(12, 'gone', 'Leaves Baltimore with the Greek')],
      offLadder: 'Second to the Greek and the face of the business. Nobody is promoted under him this season; they are paid, passed down or arrested.' }],
    ['sergei', { tier: 2, short: 'Sergei', name: 'Sergei Malatov', alias: 'Serge', title: 'Driver and muscle',
      status: [S(11, 'arrested', 'Arrested in the warrant sweep'), S(12, 'cooperating', "Names Vondas as the crewman's killer")],
      offLadder: 'The middle layer, the one that gets arrested. The Greek expects his men to stand for him; Sergei holds out for a day.' }],
    ['eton', { initials: 'ET', tier: 2, short: 'Eton', title: 'Runs the drug sales',
      status: [S(11, 'arrested', 'Arrested in the warrant sweep')],
      offLadder: 'The middle layer, the one that gets arrested.' }],
    ['glekas', { tier: 2, short: 'Glekas', name: 'George Glekas', alias: 'Double G', title: 'Fence; Highlandtown store',
      status: [S(10, 'dead', 'Shot dead by Ziggy')],
      offLadder: 'The Greeks\' fence. He is killed by an outsider over car money, and the Greeks strip his store so it leads nowhere.' }],
    ['ilona', { tier: 3, short: 'Ilona', name: 'Ilona', title: 'Madam of the brothel',
      status: [S(11, 'arrested', 'Arrested in the warrant sweep')] }],
    ['sam', { tier: 3, short: 'Sam', name: 'Sam', title: 'Crewman, Atlantic Light', unit: "Ship's crew",
      status: [S(2, 'dead', 'Throat cut by Vondas')] }],
    ['whitemike', { tier: 3, short: 'White Mike', name: 'White Mike', title: 'Dealer; buys from the Greeks',
      status: [S(11, 'cooperating', 'Arrested; gives up Eton and Sergei')],
      offLadder: 'A customer, not a member: the Greeks\' heroin reaches him through Eton\'s warehouse.' }],
    ['frog', { tier: 3, short: 'Frog', title: 'Corner dealer, Southeast',
      offLadder: 'The bottom of the chain that runs from the Greeks through the Sobotka cousins.' }],
  ],

  relationships: {
    drop: [
      'omar>nathan>legal', 'ziggy>cheese>conflict', 'propjoe>sergei>friendship', 'valchek>krawczyk>political',
      'frank>daniels>informant', 'sergei>daniels>informant',   // kept as frank>beadie and sergei>bunk
    ],
    dropEp: ['propjoe>stringer>business>9'],                   // the ep 9 deal is the supply tie below
    dedupe: [
      'propjoe>vondas>business', 'koutris>greek>informant', 'greek>koutris>informant', 'ziggy>glekas>killed', 'sergei>cheese>conflict',
      'whitemike>mcnulty>informant', 'nick>daniels>informant', 'daniels>greek>investigates', 'fitzhugh>koutris>investigates',
      'valchek>frank>conflict', 'valchek>frank>investigates', 'levy>avon>legal', 'bubbles>mcnulty>informant', 'bubbles>kima>informant',
      'beadie>frank>friendship', 'beadie>maui>romance', 'daniels>frank>investigates', 'freamon>horseface>investigates',
      'bunk>horseface>investigates', 'herc>nick>investigates', 'cole>bodie>investigates', 'kima>stringer>investigates',
      'krawczyk>davis>political', 'propjoe>nick>business',
    ],
    label: {
      ...capitalizedPoliceLabels(),
      'koutris>greek>informant': 'Passes FBI information to the Greek',
      'whitemike>mcnulty>informant': 'Gives up Eton and Sergei to McNulty and Greggs',
      'nick>daniels>informant': "Gives up Vondas, Eton and Sergei and picks out the Greek's photo",
      'daniels>greek>investigates': 'The detail follows the trail past Vondas to the Greek',
      'fitzhugh>koutris>investigates': 'Works out that Koutris was the leak',
      'levy>avon>legal': 'Wins Avon an earlier parole hearing for naming Tilghman',
      'bubbles>mcnulty>informant': 'Finds Omar for McNulty to work off a shoplifting arrest',
      'bubbles>kima>informant': 'Tips Kima and McNulty to the Barksdale–East Side deal to get charges dropped',
      'beadie>frank>friendship': 'Know each other from years on the docks',
      'beadie>maui>romance': "Maui is Beadie's old boyfriend; he won't inform on union men",
      'daniels>frank>investigates': "Frank is the detail's original target",
      'freamon>horseface>investigates': 'Ties the missing containers to Horseface on the port computer',
      'bunk>horseface>investigates': "Presses him about the dead women's container",
      'herc>nick>investigates': 'Herc and Carver tie Nick to Frog',
      'cole>bodie>investigates': "Questions Bodie over the guns from the boy's killing",
      'kima>stringer>investigates': 'Photographs Stringer meeting Prop Joe',
      'krawczyk>davis>political': 'Break ground together on the grain-pier condos',
      'valchek>frank>conflict': "Feud over the church window and the union's money",
      'valchek>frank>investigates': 'Trades council votes for a detail on Frank; gloats at his arrest',
      'rawls>burrell>command': 'Colonel over CID, under Burrell (line inferred)',
      'valchek>burrell>command': 'District major under Burrell (line inferred)',
      'colvin>burrell>command': 'District major under Burrell (line inferred)',
      'stringer>omar>conflict': 'Lies to him that Mouzone tortured Brandon; in ep 12 Omar works it out',
      'frank>beadie>informant': 'Agrees to cooperate after Beadie talks to him; he is dead before he can give a statement',
      'mcnulty>beadie>friendship': 'Flirt over drinks; nothing happens (ep 8)',
      'mcnulty>pearlman>romance': 'Casual affair; she ends it (ep 2)',
      'sergei>bunk>informant': "Admits Vondas killed the crewman and gives up the Greek's meeting place",
      'carver>daniels>command': "Sergeant on Daniels' detail; his rank doesn't count there",
    },
    patch: {
      'greek>koutris>informant': { type: 'business', label: 'Repays Koutris with a Colombian cocaine shipment to seize' },
      'beadie>maui>romance': { ep: null },
      'bubbles>mcnulty>informant': { ep: 4 },
      // the drug chain, as directional supply ties (source supplies target)
      'propjoe>eton>business': { s: 'eton', t: 'propjoe', type: 'supply', label: "Supplies Joe by the kilo from the Greeks' warehouse" },
      'whitemike>eton>business': { s: 'eton', t: 'whitemike', type: 'supply', label: "Supplies White Mike's re-ups from the warehouse" },
      'whitemike>nick>business': { type: 'supply', label: 'Supplies Nick once Vondas passes him down' },
      'frog>nick>business': { s: 'nick', t: 'frog', type: 'supply', label: "Supplies Frog's corner" },
      'frog>ziggy>business': { s: 'ziggy', t: 'frog', type: 'supply', label: "Frog works Ziggy's package and comes up short" },
      'ziggy>whitemike>business': { s: 'whitemike', t: 'ziggy', type: 'supply', label: 'Has fronted Ziggy packages, but refuses him another' },
      'propjoe>stringer>alliance': { type: 'supply' },
      'vargas>stringer>business': { type: 'supply' },
      'avon>roberto>business': { s: 'roberto', t: 'avon', type: 'supply', label: 'New York supplier, until the DEA targets him (ep 1)' },
      'butchie>tilghman>business': { type: 'supply', label: 'Sells Tilghman the drugs he smuggles into the prison' },
    },
    add: [
      ['stringer', 'dangelo', 'conflict', 'Paid a contact from Washington to have him killed in prison; it is staged as a suicide and kept from Avon', 6],
      ['burrell', 'grayson', 'political', "Recommends Grayson to run Valchek's first detail", 3],
      ['diggins', 'vondas', 'investigates', 'Takes Bunk and McNulty out on a "fishing trip" to watch Vondas', 10],
      ['colvin', 'bodie', 'investigates', "His district sweeps the Pit after the boy's death", 9],
      ['delores', 'ringo', 'alliance', "Hands him a bundle of Frank's cash", 3],
      ['elena', 'aimee', 'business', 'Elena, a realtor, shows Aimee and Nick a house', 5],
      ['valchek', 'lewandowski', 'conflict', "Valchek's window loses the spot in the nave to the union's", 1],
    ],
  },

  charts: [
    { id: 'union', tab: 'Union', faction: 'union',
      kicker: 'IBS Locals 1514 & 47 · the port of Baltimore', title: "The Stevedores' Union",
      blurb: 'Two locals share the docks: the checkers, who track every container, and the longshoremen, who move them. Frank runs the checkers and pays for loyalty with the Greek\'s money.',
      roots: ['frank', 'coxson'],
      units: { _1514: { label: 'Local 1514 · checkers' }, _47: { label: 'Local 47 · longshoremen' }, _pol: { label: 'Paid to lobby Annapolis' } },
      edges: [
        ['_1514', 'frank'], ['horseface', '_1514'], ['ott', '_1514'], ['maui', '_1514'], ['johnnyfifty', '_1514'], ['ringo', '_1514'], ['ziggy', '_1514'],
        ['nick', 'frank', 'dotted'], ['delores', 'frank', 'dotted'], ['_pol', 'frank', 'dotted'], ['dibiago', '_pol'],
        ['_47', 'coxson'], ['littlebigroy', '_47'], ['lala', '_47'], ['newcharles', '_47'],
      ],
      roles: {
        frank: 'Secretary-treasurer; runs the cans', coxson: 'President of Local 47',
        horseface: 'Loses the Greek\'s cans', ott: 'Next in line, by rotation', ziggy: 'Frank\'s son; low seniority',
        nick: 'Local 47; Frank\'s go-between', delores: 'Holds Frank\'s cash for members', dibiago: 'The union\'s lobbyist',
      },
    },

    { id: 'greeks', tab: 'Greeks', faction: 'greeks',
      kicker: 'Smuggling through the port', title: 'The Greeks',
      blurb: 'Drugs, stolen goods and women come in by container. Hardly anyone meets the Greek; Vondas runs the business, and outsiders are paid by the job.',
      roots: ['greek'],
      units: { _job: { label: 'Paid by the job' } },
      edges: [
        ['vondas', 'greek'], ['koutris', 'greek', 'dotted'],
        ['sergei', 'vondas'], ['eton', 'vondas'], ['glekas', 'vondas'], ['ilona', 'vondas', 'dotted'],
        ['_job', 'vondas', 'dotted'], ['frank', '_job'], ['sam', '_job'], ['nick', '_job'],
        ['propjoe', 'eton', 'dotted'], ['whitemike', 'eton', 'dotted'], ['frog', 'nick', 'dotted'], ['ziggy', 'glekas', 'dotted'],
      ],
      roles: {
        koutris: 'FBI agent; passes him news', sergei: 'Driver and muscle', eton: 'Drug sales', glekas: 'Fence; Highlandtown store',
        ilona: 'Madam; lease ties her to them', frank: 'Moves the cans, per container', sam: 'Crewman on the Atlantic Light',
        nick: 'Container numbers; then heroin', propjoe: 'Biggest wholesale buyer', whitemike: 'Buyer; supplies Nick from ep 9',
        frog: 'Sells Nick\'s packages', ziggy: 'Sells him stolen goods',
      } },

    { id: 'barksdale', tab: 'Barksdale', faction: 'barksdale',
      kicker: 'West Baltimore · run from a cell', title: 'The Barksdale Organization',
      blurb: 'Avon gives orders from prison through Stringer, who runs the business outside. The muscle is gone, so it is hired; the product is weak, so supply is bought.',
      roots: ['avon'],
      units: { _inside: { label: 'Inside with Avon' }, _side: { label: 'Family, counsel & muscle' }, _supply: { label: 'Suppliers' } },
      edges: [
        ['_inside', 'avon', 'dotted'], ['weebey', '_inside'], ['dangelo', '_inside'],
        ['_side', 'avon', 'dotted'], ['brianna', '_side'], ['levy', '_side'], ['mouzone', '_side'], ['lamar', 'mouzone'],
        ['_supply', 'avon', 'dotted'], ['roberto', '_supply'], ['vargas', '_supply'], ['propjoe', '_supply'],
        ['stringer', 'avon'], ['shamrock', 'stringer'], ['country', 'stringer'], ['cherry', 'stringer'],
        ['bodie', 'stringer'], ['puddin', 'bodie'], ['poot', 'bodie', 'dotted'],
      ],
      roles: {
        dangelo: 'Cuts himself off (ep 4)', mouzone: 'Hired from New York (ep 9)', roberto: 'New York; drops them (ep 1)',
        vargas: 'Atlanta; weak product', propjoe: 'Product at cost, from ep 9', cherry: 'Cut house', poot: 'Runs the Pit',
      } },

    { id: 'bpd', tab: 'Police', faction: 'police',
      kicker: 'Baltimore Police Department & the port police', title: 'Chain of Command',
      blurb: 'Where everyone sat when the season began. Dotted lines are informal or inferred. The Marine Unit and the port police sit outside the main chain.',
      roots: ['burrell', '_marine', '_port'],
      units: { _ec: { label: 'Evidence Control' }, _narc: { label: 'Narcotics & forfeiture' }, _marine: { label: 'Marine Unit' }, _port: { label: 'Port Authority police' } },
      edges: [
        ['rawls', 'burrell'], ['valchek', 'burrell'], ['colvin', 'burrell'], ['_ec', 'burrell', 'dotted'], ['daniels', '_ec'],
        ['landsman', 'rawls'], ['bunk', 'landsman'], ['freamon', 'landsman'], ['cole', 'landsman'], ['norris', 'landsman'],
        ['_narc', 'rawls', 'dotted'], ['kima', '_narc'], ['herc', '_narc'], ['prez', '_narc'],
        ['carver', 'valchek'], ['grayson', 'valchek'], ['polk', 'grayson'], ['santangelo', 'colvin', 'dotted'],
        ['mcnulty', '_marine'], ['diggins', '_marine'], ['beadie', '_port'],
      ],
      roles: {
        burrell: 'Deputy Commissioner; next in line', rawls: 'Colonel over CID', kima: 'Desk job, Asset Forfeiture',
        carver: 'Uniformed sergeant', grayson: 'Runs Valchek\'s first detail (ep 2)', santangelo: 'Uniformed patrol',
      },
      extra: [['prez', 'valchek', 'son-in-law; reports to him']] },

    { id: 'detail', tab: 'The Detail', faction: 'police',
      kicker: 'Formed ep 2 · remade under Daniels ep 4', title: 'The Detail',
      blurb: 'Valchek got it from Burrell in exchange for council votes. The first version was dead weight; Valchek demanded Daniels, who picked his own people and followed the case past Sobotka to the Greeks.',
      roots: ['burrell'],
      units: { _first: { label: 'Kept from the first detail' }, _narc: { label: 'From Narcotics' }, _se: { label: 'From the Southeastern' },
               _hom: { label: 'From Homicide' }, _port: { label: 'From the port police' }, _boat: { label: 'Off the boat (ep 8)' } },
      edges: [
        ['valchek', 'burrell', 'dotted'], ['grayson', 'valchek'], ['polk', 'grayson'],
        ['rawls', 'burrell'], ['daniels', 'rawls'],
        ['_first', 'daniels'], ['prez', '_first'], ['_narc', 'daniels'], ['kima', '_narc'], ['herc', '_narc'],
        ['_se', 'daniels'], ['carver', '_se'], ['_hom', 'daniels'], ['freamon', '_hom'], ['bunk', '_hom'],
        ['_port', 'daniels'], ['beadie', '_port'], ['_boat', 'daniels'], ['mcnulty', '_boat'],
        ['pearlman', 'daniels', 'dotted'], ['fitzhugh', 'daniels', 'dotted'],
      ],
      roles: {
        burrell: 'Traded the detail for votes', valchek: 'Wanted it; his grudge', grayson: 'First commander, eps 2–3',
        rawls: 'Approves its people; CID', daniels: 'Detail commander from ep 4', prez: 'The money trail',
        kima: 'Runs the street team', herc: 'Street team', carver: 'Sergeant under Greggs',
        freamon: 'Ties Sobotka to the cans', bunk: 'Brings the Jane Does (ep 7)', beadie: 'Tracks the cans',
        mcnulty: 'The brothel; tails Vondas', pearlman: 'Legal liaison (ASA)', fitzhugh: 'FBI, joint case from ep 10',
      },
      extra: [['prez', 'valchek', 'reports to his father-in-law']] },

    { id: 'informants', tab: 'Informants', faction: 'street',
      kicker: 'Who talks, and to whom', title: 'Informants',
      blurb: 'Every source in the season and who they feed: addicts, a dealer who flips, a son-in-law, a dying union, a guard Avon gives up, an FBI agent working for the other side, and one informant who doesn\'t exist.',
      roots: ['_detail', 'valchek', 'greek', '_probe', 'nathan'],
      units: { _detail: { label: 'The detail' }, _probe: { label: 'Prison overdose investigators' }, _fuzzy: { label: '"Fuzzy Dunlop" (invented)' } },
      edges: [
        ['mcnulty', '_detail'], ['kima', '_detail'], ['beadie', '_detail'], ['daniels', '_detail'], ['bunk', '_detail'], ['herc', '_detail'],
        ['bubbles', 'mcnulty', 'dotted'], ['whitemike', 'mcnulty', 'dotted'], ['shardene', 'kima', 'dotted'],
        ['maui', 'beadie', 'dotted'], ['frank', 'beadie', 'dotted'], ['nick', 'daniels', 'dotted'], ['sergei', 'bunk', 'dotted'],
        ['_fuzzy', 'herc', 'dotted'], ['prez', 'valchek', 'dotted'], ['koutris', 'greek', 'dotted'], ['avon', '_probe', 'dotted'],
        ['omar', 'nathan', 'dotted'],
      ],
      roles: {
        bubbles: 'Finds Omar; tips the tower deal', whitemike: 'Gives up Eton and Sergei (ep 11)', shardene: 'Finds a dancer who talks',
        maui: 'Won\'t inform; points to the computer', frank: 'Agrees to cooperate (ep 11)', nick: 'Gives up the Greeks (ep 12)',
        sergei: 'Names Vondas (ep 12)', herc: 'Covers a lost bug', prez: 'Tells his father-in-law', valchek: 'Prez\'s father-in-law',
        koutris: 'FBI agent leaking to the Greek', greek: 'Has a source in the FBI', avon: 'Gives up the guard Tilghman',
        nathan: 'Prosecutes Bird', omar: 'Star witness against Bird',
      } },

    { id: 'street', tab: 'Street', faction: 'street',
      kicker: 'Outside the Barksdale chain', title: 'The Street',
      blurb: 'The stick-up crew, the East Side boss with the best product in town, the blind bar owner who brokers between them, and the addicts who sell what they hear.',
      roots: ['omar', 'propjoe', 'butchie', 'bubbles'],
      edges: [
        ['dante', 'omar'], ['kimmy', 'omar'], ['tosha', 'omar'], ['cheese', 'propjoe'],
        ['tilghman', 'butchie', 'dotted'], ['johnny', 'bubbles', 'dotted'],
      ],
      roles: { cheese: 'Runs crews; three towers from ep 10', tilghman: 'Buys from him; smuggles it inside', johnny: "Bubbles' partner" },
    },

    { id: 'law', tab: 'Law & Politics', faction: 'law',
      kicker: 'Courthouse, Annapolis & the FBI', title: 'Law & Politics',
      blurb: 'They don\'t report to each other. Prosecutors make the deals, the union\'s money buys access in Annapolis, and the FBI wants the union.',
      roots: ['_sao', 'phelan', 'levy', '_pol', '_fbi'],
      units: { _sao: { label: "State's Attorney's Office" }, _pol: { label: 'Annapolis & City Hall' }, _fbi: { label: 'FBI' } },
      edges: [
        ['pearlman', '_sao'], ['nathan', '_sao'],
        ['davis', '_pol'], ['dibiago', '_pol'], ['krawczyk', '_pol'],
        ['reese', '_fbi'], ['fitzhugh', 'reese'], ['koutris', '_fbi', 'dotted'],
      ],
      roles: {
        pearlman: 'The detail\'s prosecutor', nathan: 'Prosecutes Bird', phelan: 'Tries Bird', levy: 'Defends Bird; Avon\'s deal',
        davis: 'Takes the union\'s money', dibiago: 'The union\'s lobbyist', krawczyk: 'Wants condos on the grain pier',
        koutris: 'Counterterrorism, Washington',
      } },
  ],

  ladders: [
    { id: 'game', title: 'The Game', org: 'Barksdale Organization', color: '--sodium',
      blurb: 'Same ranks as Season 1, run from a prison cell. The muscle is dead or locked up, the product is weak, and the top two stop agreeing.',
      rungs: [
        { id: 'kingpin', title: 'Kingpin', blurb: 'Owns the territory and makes the big calls. This season Avon makes them from prison, through Stringer\'s and Brianna\'s visits.' },
        { id: 'second', title: 'Second-in-command', blurb: 'Runs the business day to day. With Avon inside, Stringer runs it from a funeral home, more and more on his own judgment.' },
        { id: 'enforcer', title: 'Chief enforcer', aka: 'Top soldier', blurb: 'Avon\'s most trusted gun. With Wee-Bey serving time and Stinkum dead, the post is empty until Avon hires Brother Mouzone from New York.' },
        { id: 'soldiers', title: 'Soldiers', aka: 'Muscle', blurb: 'Protection, tails, test runs and gun disposal. Stringer complains he has no real muscle left.' },
        { id: 'crewchief', title: 'Crew chiefs', aka: 'Lieutenants', blurb: 'One crew per territory. Bodie runs a tower crew and Poot the Pit; from episode 10 Prop Joe\'s crew works three of the towers beside them.' },
        { id: 'dealers', title: 'Hand-to-hand', aka: 'Slingers', blurb: 'Sell the package under brand names Stringer keeps changing, because the product is weak.' },
        { id: 'stash', title: 'Stash & runners', blurb: 'Hold and resupply the package. Cherry runs the cut house where it is diluted.' },
        { id: 'lookouts', title: 'Lookouts', aka: 'Hoppers', blurb: 'The youngest workers watch for police and stick-up crews.', none: 'None named in Season 2' },
      ],
      levers: [
        { b: 'Supply is power.', text: 'The New York connection drops the Barksdales and the Atlanta package is weak. Stringer trades three towers to Prop Joe for product at cost (ep 9).' },
        { b: 'The king rules from a cell.', text: 'Avon has a guard sold a poisoned package, then trades the guard\'s name for an earlier parole hearing (eps 3–4).' },
        { b: 'Hire, don\'t promote.', text: 'With no muscle left, Avon brings in Brother Mouzone from New York on retainer (ep 9). He lasts until Omar shoots him.' },
        { b: 'Walking away is fatal.', text: 'D\'Angelo cuts himself off from the family (ep 4). Stringer pays to have him killed in prison and tells Avon nothing (eps 6–7).' },
      ] },

    { id: 'job', title: 'The Job', org: 'Baltimore Police Department', color: '--fluoro',
      blurb: 'Nine ranks from patrol officer to commissioner. In Season 2 a major\'s grudge and a commissioner\'s confirmation vote decide who works which case.',
      rungs: [
        { id: 'commissioner', title: 'Commissioner', blurb: 'Head of the department. Frazier is leaving for Washington; once the council votes are in (ep 9), Burrell moves up.', none: 'Frazier is leaving; not seen this season' },
        { id: 'deputy', title: 'Deputy Commissioner', aka: 'Operations', blurb: 'Runs day-to-day policing. Burrell holds it while he waits for the council to confirm him.', none: 'Nobody named once Burrell moves up' },
        { id: 'colonel', title: 'Colonel', blurb: 'Senior command rank above major. Rawls now holds it, over the Criminal Investigation Division (CID).' },
        { id: 'major', title: 'Major', blurb: 'Commands a district (Southeastern, Western) or a unit. Valchek\'s district and his council friends make him dangerous.' },
        { id: 'captain', title: 'Captain', blurb: 'The rank between lieutenant and major.', none: 'None on screen in Season 2' },
        { id: 'lieutenant', title: 'Lieutenant', blurb: 'Commands a shift, a unit or a detail. Grayson runs Valchek\'s first detail; Daniels runs the second.' },
        { id: 'sergeant', title: 'Sergeant', blurb: 'First-line supervisor. Landsman runs a Homicide squad. Carver has stripes, but on Daniels\' detail a detective runs his team.' },
        { id: 'detective', title: 'Detective', blurb: 'Plainclothes investigator. Can be detailed out of a unit, as Freamon and Bunk are, while still belonging to it.' },
        { id: 'officer', title: 'Officer', aka: 'Patrol', blurb: 'Uniformed patrol, or the Marine Unit, where McNulty is sent after the Barksdale case.' },
      ],
      levers: [
        { b: 'Favors for votes.', text: 'Valchek swings First District council votes behind Burrell\'s confirmation in return for a detail on Frank Sobotka (ep 2).' },
        { b: 'Leverage cuts both ways.', text: 'Valchek demands Daniels by name, so Daniels names his price: a permanent unit and his own people (ep 4).' },
        { b: 'Dump the cases.', text: 'Rawls tries to send the floater to the county and the container to the state. McNulty\'s tide charts keep fourteen murders in the city (eps 1–2).' },
        { b: 'Patrons.', text: 'Prez\'s father-in-law kept him in the job. After Prez punches him, Daniels talks Valchek down to desk duty and an apology (ep 12).' },
        { b: 'Stripes aren\'t command.', text: 'Carver\'s stripes came from informing on Daniels. On Daniels\' detail, Detective Greggs runs his team (ep 5).' },
      ] },

    { id: 'union', title: 'The Union', org: 'International Brotherhood of Stevedores', color: '--harbor',
      blurb: 'Seniority decides who works, the hiring hall hands out the days, and the officers are elected. On a dying waterfront, the secretary-treasurer\'s cash decides who stays loyal.',
      rungs: [
        { id: 'officers', title: 'Local officers', aka: 'Secretary-treasurer, president', blurb: 'Elected leaders of the two locals. Frank runs Local 1514 and its money; Nat Coxson is president of Local 47.' },
        { id: 'senior', title: 'Senior members', aka: 'Graybeards', blurb: 'First pick of the work at the hiring hall and weight in union votes. By rotation, Ott is due the next turn as secretary-treasurer.' },
        { id: 'members', title: 'Card-holders', blurb: 'Members of either local whose place on the seniority list the show doesn\'t spell out. They get work when the ships come in.' },
        { id: 'junior', title: 'Low seniority', blurb: 'A union card but no seniority: a day or two when ships are plentiful and nothing when they aren\'t. Nick, Ziggy and La La drink at the bar waiting for days.' },
      ],
      levers: [
        { b: 'Seniority decides who works.', text: 'The hiring hall hands out days by seniority. Ringo has 60 checkers above him and worked five days in a month (ep 3).' },
        { b: 'The boss\'s cash fills the gap.', text: 'Frank leaves money with Delores for members who can\'t get work (ep 3) and brings an envelope to New Charles\'s family (ep 7). The money is the Greek\'s.' },
        { b: 'Turns are traded, not won.', text: 'By an informal rotation between Polish and Black officers, this term is Ott\'s. Frank asks Nat for one more year (ep 7), then runs anyway (ep 10).' },
        { b: 'Loyalty outlives the law.', text: 'After Frank\'s murder the members re-elect him rather than name new officers, and the federal government padlocks the hall (ep 12).' },
      ] },
  ],
};
