// Shared helpers for the case-board tools: load season files, write them in a stable format,
// and keep the season <script> tags in index.html in sync. Node 18+, no dependencies.
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const RESEARCH_DIR = path.join(ROOT, 'research');
const INDEX = path.join(ROOT, 'index.html');
const SCHEMA = require(path.join(ROOT, 'schema.js'));

// Evaluate a browser-style data file (it pushes onto window.WIRE_SEASONS) and return what it pushed.
function loadSeasonFile(file) {
  const sandbox = { window: { WIRE_SEASONS: [] } };
  sandbox.globalThis = sandbox;
  vm.runInNewContext(fs.readFileSync(file, 'utf8'), sandbox, { filename: file });
  const list = sandbox.window.WIRE_SEASONS;
  if (list.length !== 1) throw new Error(`${path.basename(file)} should push exactly one season, pushed ${list.length}`);
  return list[0];
}

function seasonFiles() {
  if (!fs.existsSync(DATA_DIR)) return [];
  return fs.readdirSync(DATA_DIR)
    .filter(f => /^s\d+\.js$/.test(f))
    .map(f => ({ n: +f.match(/\d+/)[0], file: path.join(DATA_DIR, f) }))
    .sort((a, b) => a.n - b.n);
}

function loadAllSeasons() {
  return seasonFiles().map(({ n, file }) => {
    const S = loadSeasonFile(file);
    if (S.season !== n) throw new Error(`${path.basename(file)} declares season ${S.season}`);
    return S;
  });
}

const KEY_ORDER = ['season', 'label', 'year', 'copy', 'factions', 'relTypes', 'statuses', 'quickPicks',
  'characters', 'relationships', 'charts', 'ladders', 'episodes'];

// Stable, diff-friendly layout: one relationship per line, one pretty block per character/chart/ladder/episode.
function formatSeason(S, note) {
  const out = [];
  const indent = (txt, pad) => txt.split('\n').join('\n' + pad);
  out.push(`/* The Wire, ${S.label || 'Season ' + S.season}: hardcoded case data.`);
  out.push(`   ${note || 'Generated by tools/build-season.js from research/s' + S.season + '/. Edit the curation file and rebuild rather than editing this file by hand.'}`);
  out.push(`   Everything here is limited to what is shown or stated by the end of this season's finale. */`);
  out.push('(window.WIRE_SEASONS = window.WIRE_SEASONS || []).push({');
  const keys = [...KEY_ORDER.filter(k => k in S), ...Object.keys(S).filter(k => !KEY_ORDER.includes(k))];
  for (const k of keys) {
    const v = S[k];
    if (v === undefined) continue;
    if (['characters', 'charts', 'ladders', 'episodes'].includes(k)) {
      out.push(`  ${k}: [`);
      v.forEach(x => out.push('    ' + indent(JSON.stringify(x, null, 2), '    ') + ','));
      out.push('  ],');
    } else if (k === 'relationships') {
      out.push('  relationships: [');
      v.forEach(x => out.push('    ' + JSON.stringify(x) + ','));
      out.push('  ],');
    } else if (k === 'factions' || k === 'relTypes' || k === 'statuses') {
      out.push(`  ${k}: {`);
      Object.entries(v).forEach(([id, def]) => out.push(`    ${JSON.stringify(id)}: ${JSON.stringify(def)},`));
      out.push('  },');
    } else {
      out.push(`  ${k}: ${JSON.stringify(v)},`);
    }
  }
  out.push('});');
  return out.join('\n') + '\n';
}

function writeSeasonFile(S, note) {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  const file = path.join(DATA_DIR, `s${S.season}.js`);
  fs.writeFileSync(file, formatSeason(S, note));
  return file;
}

// Rewrite the block between <!-- seasons ... --> and <!-- /seasons --> so it lists every data/sN.js in order.
function syncIndexScripts() {
  const html = fs.readFileSync(INDEX, 'utf8');
  const eol = html.includes('\r\n') ? '\r\n' : '\n';
  const re = /(<!-- seasons:[^>]*-->\r?\n)([\s\S]*?)(<!-- \/seasons -->)/;
  if (!re.test(html)) throw new Error('index.html is missing the <!-- seasons --> ... <!-- /seasons --> markers');
  const tags = seasonFiles().map(({ n }) => `<script src="data/s${n}.js"></script>${eol}`).join('');
  const next = html.replace(re, (_, a, __, c) => a + tags + c);
  if (next !== html) fs.writeFileSync(INDEX, next);
  return seasonFiles().map(f => f.n);
}

module.exports = { ROOT, DATA_DIR, RESEARCH_DIR, INDEX, SCHEMA, loadSeasonFile, loadAllSeasons, seasonFiles, formatSeason, writeSeasonFile, syncIndexScripts };
